FROM python:2.7.14-alpine3.7

RUN apk --no-cache add curl \
    && echo "Pulling watchdog binary from Github." \
    && curl -sSL https://github.com/openfaas/faas/releases/download/0.8.0/fwatchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog \
    
RUN pip install awscli --upgrade --user

RUN apk add --no-cache less groff

ENV PATH=$PATH:/root/.local/bin/

ENV fprocess="xargs aws"
# Set to true to see request in function logs
ENV write_debug="false"

HEALTHCHECK --interval=5s CMD [ -e /tmp/.lock ] || exit 1
CMD [ "fwatchdog" ]
